modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="mushokucraft"
version="0.4.0"
displayName="Mushoku Craft"
authors="XxRaay"
description='''Hardcore RPG mod inspired by Mushoku Tensei. Completely overhauls combat, magic, crafting and world exploration.'''

[[dependencies.mushokucraft]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.mushokucraft]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.mushokucraft]]
modId="bettercombat"
type="optional"
versionRange="[1.8.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.mushokucraft]]
modId="dummmmmmy"
type="optional"
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="mushokucraft.mixins.json"
